services:
  redis:
    image: redis:7
  postgres:
    environment:
        - POSTGRES_DB=cardinal
        - POSTGRES_PASSWORD=password
    image: postgres:15
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: ./scripts/start.sh
