services:
  redis:
    image: redis:7
  postgres:
    environment:
        - POSTGRES_DB=skewlup
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    image: postgres:15
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${PORT}:3000
    command: ./scripts/start-${DEV_OR_PROD}.sh
